# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_address', models.CharField(max_length=100)),
                ('event_website', models.URLField(null=True)),
                ('event_description', models.TextField(blank=True, max_length=600, null=True)),
                ('event_image', models.URLField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('event_faq', models.TextField(blank=True, max_length=600, null=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
