# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
