# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activites', '0002_auto_20160205_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='event_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='event_longitude',
            field=models.FloatField(null=True),
        ),
    ]
